const express = require("express")
const router = express.Router()
const products = require("../controllers/shop")
router.get("/", products.index )
router.get("/description/:productId",products.productDescription)
router.post("/cart",products.postCart)
router.get("/products", products.showProduct)
router.get("/cart",products.cart)
router.get("/checkout",products.checkout)
router.get("/orders",products.orders)
router.post("/cart-delete-item",products.deleteCartItem)
module.exports = router